apiVersion: v1
kind: ReplicationController
metadata:
  name: selenium-hub 
  namespace:selenium-grid
  labels:
    app: selenium-hub
spec:
  replicas: 1
  selector:
    app: selenium-hub
  template:
    metadata:
      namespace:selenium-grid
      labels:
        app: selenium-hub
    spec:
      containers:
      - name: selenium-hub
        image: selenium/hub:2.47.1 
        ports:
          - containerPort: 4444 
        resources:
          limits:
            memory: "1000Mi"
            cpu: ".2"
        livenessProbe:
          httpGet:
            path: /grid/console
            port: 4444
          initialDelaySeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /grid/console
            port: 4444
          initialDelaySeconds: 30
          timeoutSeconds: 5
